### ISSUE TITLE
Integer OverflowException when deserializing an int64 whose value is too large to fit in an int32

### ISSUE THREAD

**Issue by Numpsy** [Zaid-Ajaj/Hawaii#15]
Hi,

I have an OpenApi schema whose return types include some Integer type fields that have a format of int64.
The Hawaii code generator generates client properties of type int64, but if I try to call the server function and it returns a value which is too large to fit in an int32, then I get this:

![image](https://user-images.githubusercontent.com/1178570/125311140-1926bc80-e32b-11eb-863d-ce71116b8e5e.png)

I had a go at debugging it and I *think* the error comes from 

https://github.com/Zaid-Ajaj/Fable.Remoting/blob/ea1a681100bcfcb02accf81e1fcad6899e7d1a32/Fable.Remoting.Json/FableConverter.fs#L452

where it tries to convert the JSON value into an ```int```, before upcasting to a ```(u)int64``` (and then fails if the value is too large for an int32)?

It actually appears to work ok if the target client property is an ```Option<int64>``` rather than a plain ```int64``` (different code paths in the json converter I think?).

Fwiw, I actually fell over this while having a look at making Snowflaqe understand custom 'Long' types (ref https://github.com/Zaid-Ajaj/Snowflaqe/issues/8#issuecomment-863949647) and then tried in Hawaii as well (given that int64 is part of the main spec here, where it's an extension in GraphQl)

**Comment by Zaid-Ajaj** [comment]
Hi there @Numpsy that's an interesting issue. Do you have a piece of the JSON string that you were trying to deserialize for me? I'll have a go at it

**Comment by Zaid-Ajaj** [comment]
BTW, I must have overlooked your issue on recognizing the `Long` custom type by Snowflaqe into `int64`. It should be easy to have it built-in

**Comment by Zaid-Ajaj** [comment]
Should be fixed in v0.29 can you give a try and confirm the fix?

**Comment by Numpsy** [comment]
Thanks, my case looks ok now :-)

(/sorted in the time I spent watching an F# intro on the .net docs docs, /has much to learn! :-))

**Comment by Zaid-Ajaj** [comment]
Yeah I was fixing it while listening to .NET docs in the background xD
