### ISSUE TITLE
CLI problems

### ISSUE THREAD

**Issue by travis-leith** [Zaid-Ajaj/Hawaii#20]
noticed some issues with the CLI

`--version` reports the [wrong number](https://github.com/Zaid-Ajaj/Hawaii/blob/135e1643af2c573e5da8aad23fb072cab0429902/src/Program.fs#L3109)

I tried to use `--show-tags` with `--config`, which did not work but [I see now](https://github.com/Zaid-Ajaj/Hawaii/blob/135e1643af2c573e5da8aad23fb072cab0429902/src/Program.fs#L3144) that it expects a file path without a `--config` keyword. Would be good if there was a `--help` detailing the interface in full.

On a related note, would you be open to porting the CLI to [Argu](https://fsprojects.github.io/Argu/)? Gives you `--help` for free and makes it easy to conform to the style of other F# tools such as paket. If yes, I can work on a PR this weekend.

**Comment by Zaid-Ajaj** [comment]
Thanks for the raising the issue 🙏 I knew I had forgot something with `--version` 😅 Just fixed that as of v0.44 as well as making `--show-tags` consistent with `--config`. 

> would you be open to porting the CLI to Argu?
Not a big fan tbh, I like the simplicity of just by pattern matching against an array of strings. For now, I want to keep it as such but might reconsider it another time
