### ISSUE TITLE
How to get the "@odata.type" entries in the serialized content?

### ISSUE THREAD

**Issue by travis-leith** [Zaid-Ajaj/Hawaii#21]
As is, the generated code creates a body that looks something like this

```
{
	"ExtractionRequest": {
		"ContentFieldNames": [
			"RIC",
			"Round Lot Size",
			"ISIN",
			"Currency Code"
		],
		"IdentifierList": {
			"InstrumentIdentifiers": [
				{
					"Identifier": "IBM.N",
					"IdentifierType": "Ric"
				}
			]
		},
		"Condition": {
			"FixedIncomeRatingSources": "None"
		}
	}
}
```

But the API I am using will only work if I POST it something like this

```
{
	"ExtractionRequest": {
		"@odata.type": "#DataScope.Select.Api.Extractions.ExtractionRequests.TermsAndConditionsExtractionRequest",
		"ContentFieldNames": [
			"RIC",
			"Round Lot Size",
			"ISIN",
			"Currency Code"
		],
		"IdentifierList": {
			"@odata.type": "#DataScope.Select.Api.Extractions.ExtractionRequests.InstrumentIdentifierList",
			"InstrumentIdentifiers": [
				{
					"Identifier": "IBM.N",
					"IdentifierType": "Ric"
				}
			]
		},
		"Condition": {
			"FixedIncomeRatingSources": "None"
		}
	}
}
```

For reference the API I am using is found at "https://selectapi.datascope.refinitiv.com/RestApi/v1/Extractions/$metadata"

**Comment by Zaid-Ajaj** [comment]
Hmm this could be a bit problematic. Is this the same for every OData service?

**Comment by travis-leith** [comment]
> Hmm this could be a bit problematic. Is this the same for every OData service?

I don't know if this requirement is universal, unfortunately.
I see that there are multiple types that all look the same, and would all have the same json representation as above, just with a different name.

Maybe the solution is to have a serializer with a srtp constrained to have a member `OdataType: string option`. The serializer then injections this string into the json if it exists.

Not sure how to know which types need this, since everything generated from "https.../v1/Authorization/$metadata" works fine as is. But in the auth schema there are no duplicated "type shapes" like there are in the extractions schema.

Alternatively you can rebrand Hawaii as an OpenApi generator only :wink:

**Comment by Zaid-Ajaj** [comment]
> I see that there are multiple types that all look the same, and would all have the same json representation as above, just with a different name.

I think I can actually workaround it but it might need some extra work. Will keep you posted 😉

**Comment by Zaid-Ajaj** [comment]
Fixes as of v0.46 where `@odata.type` are automatically added to the request and their values are statically populated in the `Create` functions. Can you give this another type?

**Comment by travis-leith** [comment]
I copied over the new type defs to my testing project.
For some reason the odata.type is not making it into the serialized string.
Also if, from visual studio, I debug and hit Shift+f9 to quick inspect, I do not see the field there. Could be related?
I do see the field if I `printfn "%A"`.

**Comment by travis-leith** [comment]
Would it be too hacky to use the exact same solution, but instead call the field `AtOdataType` and then do some sort of string search and replace after serialization to correct the name? Only downside (other than being a bit hacky) is that if someone wanted to use that as an actual field name it would break.

**Comment by Zaid-Ajaj** [comment]
> For some reason the odata.type is not making it into the serialized string

Are you constructing the instance using the `Create` function? Because the only reason the field wouldn't be available in the JSON would be if the value was `None` 🤔 I'll do some testing myself. It's really weird that it isn't coming up in the JSON 😓 

> Would it be too hacky to use the exact same solution, but instead call the field AtOdataType and then do some sort of string search and replace after serialization to correct the name? 

Yeah it sounds too hacky, this current solution looks hacky in itself tbh 😅

**Comment by travis-leith** [comment]
Just tested the hacky solution, and it worked. Which suggests the problem is with the serializer.

**Comment by travis-leith** [comment]
Also, setting a value to None, leads to the JSON being `"field" = null`, which might be a problem itself, at least for the API I am testing against. Will do further testing to verify and open another issue if needed.

**Comment by Zaid-Ajaj** [comment]
The serializer seems to be the problem for some reason 😓 will look into it tomorrow again

**Comment by travis-leith** [comment]
Is this useful at all? https://stackoverflow.com/questions/26820275/how-to-deserialize-odata-json

**Comment by Zaid-Ajaj** [comment]
I actually don't mind the solution with the `[<JsonProperty>]` it's just that it didn't work for me when I tested it 😢 do you have a working test with it?

**Comment by travis-leith** [comment]
I do have a working test with it. Note that it doesn't work with ` ``@odata.type`` `, I could only get it to work with an 'allowed' F# name.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot for helping me with the testing! First I tried using `JsonProperty` with property name called `@odata.type` but it didn't work so I discounted the idea of using `JsonProperty` with another property name. Now it should work though as of v0.48 🚀 this time we got it for sure 🤞 🤞

**Comment by travis-leith** [comment]
Looks good!
