### ISSUE TITLE
Urls containing [ and ] generates code that does not compile

### ISSUE THREAD

**Issue by yodiz** [Zaid-Ajaj/Hawaii#27]
If the URL contains [ ] the types name will contain it as well and generate compilation errors.

According to https://fsharp.org/specs/language-spec/4.0/FSharpSpec-4.0-latest.pdf in section "3.4 Identifiers and Keywords"

_Note that when an identifier is used for the name of a types, union type case, module, or namespace, the following characters are not allowed even inside double-backtick marks:
‘.', '+', '$', '&', '[', ']', '/', '\\', '*', '\"', '`'

Maybee exchange thoose chars to something or remove them when generating the Client.fs?

**Comment by yodiz** [comment]
Hi and thanks,

Maybee my manufactured test-file wasn't that great.

Your change removes [, but still leaves ] in the typenames :)

in cleanOperationName:
```
    elif operation.Contains "[" then
        operation.Split('[', StringSplitOptions.RemoveEmptyEntries)
        |> Array.map capitalize
        |> String.concat ""

    elif operation.Contains "]" then
        operation.Split(']', StringSplitOptions.RemoveEmptyEntries)
        |> Array.map capitalize
        |> String.concat ""
```

Only one of the replacement will occour as i understand the code correctly. 

Maybee replace with something like this?:
```
    let rec cleanOperationName (operationName: string) =
        let operation = operationName.Replace("{", "").Replace("}", "")

        if operation.Contains "?" then
            match operation.Split '?' with
            | [| path; parameters |] ->
                let queryParams =
                    parameters.Split([|'&'; '=' |], StringSplitOptions.RemoveEmptyEntries)
                    |> Array.map (fun part -> part.Replace("{", "").Replace("}", ""))
                    |> Array.distinctBy id
                    |> Array.map capitalize
                    |> String.concat "And"
                cleanOperationName (path + "By" + queryParams)
            | _ ->
                operation.Split([| '?'; '='; '&' |], StringSplitOptions.RemoveEmptyEntries)
                |> Array.map capitalize
                |> String.concat ""
                |> cleanOperationName
        else
            let invalidChars = [|
                '-'; '#'; '_';
                '.'; '+'; '$'; '&'; '['; ']'; '/'; '\\'; '*'; '"'; '`'
                |]
            operation.Split(invalidChars, StringSplitOptions.RemoveEmptyEntries)
            |> Array.map capitalize
            |> String.concat ""
```

**Comment by Zaid-Ajaj** [comment]
Thanks @yodiz for the _proper_ fix, I should've tested it better. I implemented your proposal and it should be part of Hawaii v0.54, can you please give it another try?

**Comment by yodiz** [comment]
Seams to work perfectly now :) Thanks!

**Comment by Zaid-Ajaj** [comment]
Awesome! thanks for confirming 🙏
