### ISSUE TITLE
Add capability to also generate Openapi spec file from F# project?

### ISSUE THREAD

**Issue by jkone27** [Zaid-Ajaj/Hawaii#29]
https://khalidabuhakmeh.com/generate-aspnet-core-openapi-spec-at-build-time 

it would be nice if hawaii also allowed for openapi spec generation in yaml or json format,

as currently swashbuckle doesnt work for functional aspnetcore frameworks (Giraffe/Falco/Saturn etc..).

So could be really useful but I understand is something completely different and maybe this project is not the right place?

this is not supported/usable 
https://github.com/rflechner/SwaggerForFsharp
https://github.com/pimbrouwers/Falco/issues/49#issuecomment-998908280
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2300

Thank you so much for hawaii

**Comment by Zaid-Ajaj** [comment]
Hi @jkone27, 

I am aware of this pain point in F# web frameworks but I am afraid Hawaii isn't the place to implement such feature. Hawaii is only concerned with generating clients for any OpenApi specification, regardless of the backend exposing those specifications. This is already quite the challenge so I don't think Hawaii will tackle such problem any time soon :/

**Comment by jkone27** [comment]
this project was really good but for some reasons has been archived... 
https://github.com/akhansari/FSharp.OpenApi
