### ISSUE TITLE
System.NullReferenceException on Homebridge schema

### ISSUE THREAD

**Issue by sergey-tihon** [Zaid-Ajaj/Hawaii#30]
Just tried Hawaii `0.55.0` on [Homebridge OpenApi schema](https://gist.github.com/sergey-tihon/71f8f9cdcfd3d21cd9e2931b8ff73055) with `hawaii.config` 
```json
{
    "schema": "./Homebridge.OpenAPI.json",
    "output": "./Homebridge.API",
    "project": "Homebridge.API",
    "target": "fable",
    "synchronous": false,
    "asyncReturnType": "async"
}
```

and it failed with NRE
```

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Program.readParamType@1927(CodegenConfig config, OpenApiSchema schema) in C:\projects\Hawaii\src\Program.fs:line 1928
   at Program.readParamType@1927(CodegenConfig config, OpenApiSchema schema) in C:\projects\Hawaii\src\Program.fs:line 1953
   at Program.operationParameters(OpenApiOperation operation, List`1 visitedTypes, CodegenConfig config) in C:\projects\Hawaii\src\Program.fs:line 2043
   at Program.createOpenApiClient(OpenApiDocument openApiDocument, List`1 visitedTypes, CodegenConfig config) in C:\projects\Hawaii\src\Program.fs:line 2277
   at Program.runConfig(String filePath) in C:\projects\Hawaii\src\Program.fs:line 3140
   at Program.main(String[] argv) in C:\projects\Hawaii\src\Program.fs:line 3268
```

Would be nice to provide more details about the issue if schema is in unexpected format.

**Comment by Zaid-Ajaj** [comment]
Hi @sergey-tihon, thanks for filing the issue. Just published v0.57 of Hawaii and it should now generate a client successfully. The problem is, looking at the the schema, it seems to be missing a lot of return types for the available operations:
```json
"responses": {
  "200": { 
    "description": ""
  }
}
```
Consider [overriding the schema](https://github.com/Zaid-Ajaj/Hawaii#advanced---overriding-the-schema) in the config with additional types in the schema to make Hawaii generate something usable:

Example:
```json
{
  "schema": "./Homebridge.OpenAPI.json",
  "output": "./Homebridge.API",
  "project": "Homebridge.API",
  "target": "fable",
  "overrideSchema": {
    "paths": {
      "/api/plugins/lookup/{pluginName}": {
        "get": {
          "responses": {
            "200": {
              "description": "",
              "content": {
                "application/json": {
                  "schema": {
                    "type": "object"
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by sergey-tihon** [comment]
Thank you @Zaid-Ajaj for such quick fix!
I did not expect almost midnight Jan 1 release. Happy New Year!

**Comment by sergey-tihon** [comment]
One more strange thing, code generated by Hawaii does not compile by default
![image](https://user-images.githubusercontent.com/1197905/147848569-f01da9c2-b596-41ab-b1b8-cb9599f83a17.png)

Looks like the issues is in `.`(dot) inside the name.
Here is the link to [Fable REPL](https://fable.io/repl/#?code=C4TwDgpgBABjASB7AthARgJwJYBMDmEAdAIIAKAkgMIA2WEAdsHABQCuG1AXFAM7Db08AGigALCAEMcEDD258BeKLT4BKKAF4AUFF1R6EAO5sO8-lkHqNsBCnTZ8RMlVoMmME9REBtALqqgA&html=Q&css=Q)

Issue is not super critical and easy to fix manually
