### ISSUE TITLE
Testing with APIs.guru

### ISSUE THREAD

**Issue by sergey-tihon** [Zaid-Ajaj/Hawaii#4]
Here (https://apis.guru/browse-apis/) you can find about 3.6k different real-world schema definition that you can use for testing. 

This https://api.apis.guru/v2/list.json json captains catalog of schema urls with version information.
You can read it, choose schemas that you like and run Hawaii on these schemas 

Some code may be reused from [here](https://github.com/fsprojects/SwaggerProvider/blob/master/tests/SwaggerProvider.Tests/APIs.guru.fs)

APIs.guru was very useful when I wrote my swagger(v2) parser, helped my find infinity recursion on compilation of recursively-dependent types and helped me validated that compiler is able to compile generated  types.

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @sergey-tihon 🙏 the catalog of schema urls will be great for testing. Let's see what rabbit hole of edge cases I will find 😄

**Comment by Zaid-Ajaj** [comment]
Added this as part of the build project to generate and build the first `n` schemas from the API guru catalog where `n = 20` right now:
```bash
cd ./build
dotnet run -- integration
```
Thanks again @sergey-tihon :heart:
