### ISSUE TITLE
Improper management of connection errors

### ISSUE THREAD

**Issue by francotiveron** [Zaid-Ajaj/Hawaii#40]
this is one of the get calls coded by the generator

```
    member this.GetGetMdp() =
        async {
            let requestParts = []
            let! (status, content) = OpenApiHttp.getAsync url "/get-mdp" headers requestParts
            return GetGetMdp.OK(Serializer.deserialize content)
        }
```

If the call fails (for example because of network disconnection), getAsync doesn't throw. The returned status is 0 and the content is empty "".  Then the code attempts to deserialize "" and obviously fails with a serialization exception. The point is, there is no way for the user to distinguish genuine json problems from network connection problem, as both result in a json parsing exception.

Is there a way to differentiate between them?

**Comment by Zaid-Ajaj** [comment]
Hi there @francotiveron, thanks for filing the issue. Currently, there isn't a way to tell that there was a connection error. I believe this is only the Fable side of things. 

One way we could fix this is by adding a `NetworkError` union case to all response types and returning that when the status code is 0
```fs
    member this.GetGetMdp() =
        async {
            let requestParts = []
            let! (status, content) = OpenApiHttp.getAsync url "/get-mdp" headers requestParts
            if status = 0 then
              return GetGetMdp.NetworkError
            else
              return GetGetMdp.OK(Serializer.deserialize content)
        }
```
or another way is to raise an exception instead
```fs
    member this.GetGetMdp() =
        async {
            let requestParts = []
            let! (status, content) = OpenApiHttp.getAsync url "/get-mdp" headers requestParts
            if status = 0 then
              return raise (new Exception("Network error occured while calling GetGetMdp"))
            else
              return GetGetMdp.OK(Serializer.deserialize content)
        }
```
What do you think?

**Comment by francotiveron** [comment]
Hi @Zaid-Ajaj  and thank you for your prompt answer
Of the two solutions you propose I prefer the second, as this is a 'non expected' scenario.

As a couple of personal notes:
- If it is not too much of a trouble, I would create a specific exception type, like NetworkError, instead of simply throwing an Exception
- IMHO this kind of exception should be thrown earlier in SimpleHttp.send function by intercepting onerror. This is because, apparently, inferring a network error from XMLHttpRequest DONE+status=0 is not standard

**Comment by francotiveron** [comment]
Any progress on this?

**Comment by Zaid-Ajaj** [comment]
Hi @francotiveron I haven't been working on this issue due to lack of time. Is there any chance you could contribute to the project? I would be happy to review, merge and publish PRs 🙏

**Comment by francotiveron** [comment]
Latest updates now use task and not async, HttpClient exceptions are propagated to the user which fixes the issue.
