### ISSUE TITLE
Wrong version is printed when calling hawaii --version

### ISSUE THREAD

**Issue by vschep** [Zaid-Ajaj/Hawaii#43]
When calling 
`hawaii --version`
the version 0.59.0 is printed instead of version 0.62.0.

See Hawaii\Program.fs:2938.

Btw. thanks for this great tool! :)

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @vschep for pointing this out! Fixed as of v0.63.0 which should print out the correct version now 😄
