### ISSUE TITLE
Fails on Application Insights Open API spec

### ISSUE THREAD

**Issue by isaacabraham** [Zaid-Ajaj/Hawaii#5]
Tested [this](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2021-03-08/workbooks_API.json) URI out.

Hawaii correctly generates a project with some types; however, the project does not build with several errors e.g.

```
The type 'WorkbookProperties' is not defined
```

`WorkbookProperties` does not appear to be a oneOf case from what I can see.

**Comment by Zaid-Ajaj** [comment]
Hi @isaacabraham thanks for trying it out! I will try to see why the type isn't generated correctly

**Comment by isaacabraham** [comment]
Hope that this is useful - happy to continue testing it out :-)

**Comment by Zaid-Ajaj** [comment]
I found out the problem with the error `The type 'WorkbookProperties' is not defined` and it was an easy fix but another big problem came into light which is that external type definitions as references were not resolved, i.e. things like 
```
"$ref": "../../../../../common-types/resource-management/v1/types.json#/parameters/SubscriptionIdParameter"
```
Which is blocked by [OpenAPI.NET/issues/609](https://github.com/microsoft/OpenAPI.NET/issues/609)

Right now, I am trying to workaround it by preprocessing the OpenAPI schema to turn relative references into absolute ones. It is a shot in the dark but will give it a try anyways

**Comment by Zaid-Ajaj** [comment]
Hi @isaacabraham this was a bit of a rollercoaster 😅 I think I got it correctly now. As of Hawaii v0.2.0 I've implemented a resolution mechanism for external references using relative paths (option `resolveReferences: true`). Also added some improvements regarding parameter naming and default responses which AppInsights seems to be using a lot. 

Can you please update Hawaii to 0.2.0 like this
```
dotnet tool update -g hawaii
```
then you should be able to generate a project using the following configuration
```json
{
    "schema": "https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2021-03-08/workbooks_API.json",
    "project": "AppInsights",
    "output": "./output",
    "resolveReferences": true
}
```
Give it a try and let me know how it goes 😄

**Comment by isaacabraham** [comment]
Compiles!
