### ISSUE TITLE
$expand element created

### ISSUE THREAD

**Issue by isaacabraham** [Zaid-Ajaj/Hawaii#6]
Sample URI 'https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/storage/resource-manager/Microsoft.Storage/stable/2021-04-01/storage.json'. Generates code that contains the following:

```fsharp
                  if $expand.IsSome then
                      RequestPart.query ("$expand", $expand.Value) ]
```

**Comment by Zaid-Ajaj** [comment]
Thanks for the issue report! Fixes as of v0.3.0 🚀 should be available from nuget in a minute. 

The parameter names are normalized but their values are persisted, meaning you get this
```fs
if expand.IsSome then RequestPart.query ("$expand", expand.Value) ]
```
The same is already happening for `api-version` which becomes `apiVersion` 😉
